INSERT INTO BOOKS (BOOKID, BOOKNAME, AUTHOR, PRICE ) VALUES(10003,  'Ikigai', 'Suntus', 300);

INSERT INTO BOOKS (BOOKID, BOOKNAME, AUTHOR, PRICE  ) VALUES(10004,  'POWER OF SUBCONCIOUS MIND', 'Edward Gosling', 500);